version: "3.7"

services:
  dashboard:
    build: .
    ports:
      - "4000:4000"
      - "3000:3000"
    networks:
      - intern
  mongodb:
    image: mongo:3.6
    ports:
      - "27017"
    networks:
      - intern
    volumes:
      - data:/data

volumes:
  data:

networks:
  intern:
